name: Update data python

on:
  schedule:
    - cron: "*/5 0 * * *" 
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  run_python_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  

      - name: Install Python packages
        run: |
          pip install --upgrade pyodbc pandas pandas-ta sqlalchemy numpy

      - name: List files in directory (optional for debugging)
        run: |
          ls  # List files in the current directory

      - name: Run Python scripts
        run: |
          python vol_volt_metrics.py
          python momentum.py
          python overlap.py
          python trend.py
