# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name:  Daily Refresh momentum

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install Python packages
      run: |
        pip install --upgrade pyodbc pandas pandas-ta sqlalchemy numpy

    - name: Install dependencies
      run: |
        pip install -U git+https://github.com/twopirllc/pandas-ta

    - name: Run Python script
      continue-on-error: true
      run: python momentum.py
